module.exports = {
  REQUIRED_VALUE: "REQUIRED_VALUE",
  MIN_CHAR_LENGTH: "MIN_CHAR_LENGTH",
  MUST_BE_DATE_VALUE: "MUST_BE_DATE_VALUE",
  DATE_TIME_MUST_BE_FUTURE_DATE: "DATE_TIME_MUST_BE_FUTURE_DATE",
  INVALID_VALUE: "INVALID_VALUE",
  INVALID_EMAIL_VALUE: "INVALID_EMAIL_VALUE",
};
